### ISSUE TITLE
Migrate to v5 of react-icons-ng

### ISSUE THREAD

**Issue by abhi1693** [icoretech/airbroke#297]
I noticed that your project uses our [react-icons-ng](https://github.com/Onemind-Services-LLC/react-icons-ng) library. We have recently migrated to GitHub NPM registry (https://github.com/Onemind-Services-LLC/react-icons-ng/issues/15#issuecomment-1676020277).

**Comment by masterkain** [comment]
hello, yeah but I'm hitting this issue https://github.com/Onemind-Services-LLC/react-icons-ng/issues/15#issuecomment-1683801720 will try again in a bit

**Comment by masterkain** [comment]
package is not installable cause github wants a github token even for public packages
