### ISSUE TITLE
OAuth Keycloak error

### ISSUE THREAD

**Issue by vespersio** [icoretech/airbroke#672]
Airbroke version: 1.1.57
Keycloak version: 25.0.2
Postgresql version:  15.7
Deployed in kubernetes cluster

First login with Keycloak
Error in browser: `Try signing in with a different account.`
Error in log:
```
[next-auth][error][adapter_error_linkAccount] 
https://next-auth.js.org/errors#adapter_error_linkaccount 
Invalid `prisma.account.create()` invocation:
***
    refresh_expires_in: 86400,
    ~~~~~~~~~~~~~~~~~~
***
Unknown argument `refresh_expires_in`. Available options are listed in green.
***
```
User created in DB after error, but next login error in browser:
`To confirm your identity, sign in with the same account you used originally.`

**Comment by masterkain** [comment]
https://github.com/nextauthjs/next-auth/issues/7129

**Comment by masterkain** [comment]
hello,
thanks for the report, I pushed version `1.1.58` if you can try and see if the problem is fixed

**Comment by vespersio** [comment]
Hi
Needed to drop db, but everything is working now. TY!
